const FORBIDDEN_TITLE = '403';
const CAPTCHA_IS_NEEDED_TITLE = 'Ой!';
const PRICES_RANGE_CLASSNAME = '_1S8ob0AgBK';
const OUT_OF_STOCK_CLASSNAME = 'Ca_h1ZgLxJ';
const SINGLE_PRICE_CLASSNAME = '_3NaXxl-HYN';

module.exports = { FORBIDDEN_TITLE, CAPTCHA_IS_NEEDED_TITLE, PRICES_RANGE_CLASSNAME, OUT_OF_STOCK_CLASSNAME, SINGLE_PRICE_CLASSNAME }